name: 'ci/cd npm package publish'

on:
  push:
    branches:
      - master
  pull_request:
    branches: '*'

env:
  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  # NODE_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: show importante variables
        run: |
          echo ${{ github.ref }}
          echo $NPM_TOKEN
          echo $GITHUB_TOKEN

  publish:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    needs: [test]
    steps:
      - name: setup-checkout
        uses: actions/checkout@v2
      - name: setup-node
        uses: actions/setup-node@v2
        with:
          node-version: 16
          # registry-url: https://registry.npmjs.org
      - name: build-scripts
        run: |
          npm install
          npm run build
      - name: publish things
        run: npm run semantic-release
      # - name: publish package
      #   run: npm publish --access public
